### ISSUE TITLE
Can't use package with SPM

### ISSUE THREAD

**Issue by nkleemann** [adamnemecek/WebMIDIKit#17]
Hey Adam,

I'm trying to test your package in a minimal setup. I added it as required in my `Package.swift`:

```swift
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "WebMidiKitTest",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/adamnemecek/WebMIDIKit.git", majorVersion: 1)
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "WebMidiKitTest",
            dependencies: ["WebMIDIKit"]),
        .testTarget(
            name: "WebMidiKitTestTests",
            dependencies: ["WebMidiKitTest"]),
    ]
)
```

But when I run `swift build` I get the following error message:

```
/Users/nik/proj/IDEs/Xcode/WebMidiKitTest: error: manifest parse error(s):
/Users/nik/proj/IDEs/Xcode/WebMidiKitTest/Package.swift:11:10: error: ambiguous reference to member 'package'
        .package(url: "https://github.com/adamnemecek/WebMIDIKit.git", majorVersion: 1)

```

I tried changing `majorVersion: 1` to `from: "1.0.0"` which seems to atleast conform to the function signature but this gave the following error:

```
Updating https://github.com/adamnemecek/WebMIDIKit.git
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
    https://github.com/adamnemecek/WebMIDIKit.git @ 1.0.0..<2.0.0
```

Can you help me out here? Really depend on your library for a generative music project, thanks :)

**Comment by adamnemecek** [comment]
I'm out until tomorrow night. I'll take a look tomorrow or on Wednesday.

**Comment by nkleemann** [comment]
Do you have any updates on this?

**Comment by bensinlukt** [comment]
Same issue here.

**Comment by nkleemann** [comment]
Trying to use this package by using Xcode 11's new SPM integration, similar error message:

```
The package dependency graph can not be resolved; unable find any available tag for the following requirements:

https://github.com/adamnemecek/WebMIDIKit.git — 1.0.5..<2.0.0
```

If you have no time for fixing this yourself can you at least give us a hint so we can try to fix it ourselves?

**Comment by adamnemecek** [comment]
My spm skills are really rusty. I guess try forking it and updating the tag version?

**Comment by nkleemann** [comment]
The format of your Package.swift file was deprecated since Swift 4 - after fixing this I could add this package with Xcode 11 by selecting "branch: master" instead of "version: 1.0.5". 

Fixed in my [fork](https://github.com/nkleemann/WebMIDIKit) 🙂

**Comment by adamnemecek** [comment]
You can create a pull request

**Comment by nkleemann** [comment]
Done
