### ISSUE TITLE
Capacitor Plugin

### ISSUE THREAD

**Issue by joshstovall** [adamnemecek/WebMIDIKit#23]
I have a Capacitor app, and have been looking for a iOS MIDI solution.  This seems promising, I am wondering if anyone has had experience using this as a [Capacitor Plugin](https://capacitorjs.com/docs/plugins/ios)?

PS... I ran into a few issues trying to build this (and the demo project) in Xcode 12.1.

**Comment by adamnemecek** [comment]
I don't have experience with Capacitator but looking at the docs, I'm guessing that supporting it should be straight forward. You probably just need to create new classes that wrap the WebMIDIKit objects.

Yeah, this project isn't exactly updated, I have moved on from Swift to Rust.
