### ISSUE TITLE
Swift package - missing manifest specification

### ISSUE THREAD

**Issue by qalvapps** [adamnemecek/WebMIDIKit#31]
encountered on Xcode 12.5 and Xcode 13.1

the manifest is missing a Swift tools version specification; consider prepending to the manifest '// swift-tools-version:5.4.0' to specify the current Swift toolchain version as the lowest Swift version supported by the project; if such a specification already exists, consider moving it to the top of the manifest, or prepending it with '//' to help Swift Package Manager find it

**Comment by adamnemecek** [comment]
Want to do a PR?

**Comment by abulka** [comment]
Is there a way of working around this issue? I "added the package anyway" but Xcode still complains and the project refuses to build. 

I'm just learning Xcode swift - where is this manifest to be found and how do I edit it?

**Comment by designerfuzzi** [comment]
after reading line by line guessing the API is conceptional and not ready. Which is , i guess, why there is no conversation about the code but invitation to do the work. After double checking the implementation i see major flaws compared to the CoreMidi C API .. in example this..
```
internal init(_ type: MIDIObjectType) {
        switch type {
        case .source:
            self = .input
        case .destination:
            self = .output
        case .other:
            fatalError("You didn't initialize a virtual port")
        default:
            fatalError("Unexpected port type \(type)")
        }
    }
```
there are not virtual port types in CoreMIDI, just input or output. a Virtual Port is always either an input or output just that parts are wise versa switched .. which allows CoreMIDI to send (in example Notes) via receiving and receiving via sending. 
Even worse, the code introduces a fataError where it does not belong.

**Comment by adamnemecek** [comment]
@designerfuzzi its an open source project. I provide no guarantees. Feel free to open any PRs as you see fit.

**Comment by designerfuzzi** [comment]
ok.. that tells me it was more of a proposal and not ready made part of AudioKit. Despite things are so desperate it is indeed needed. What i can't tell yet is how latency and speed is going with WebMidiKit (which would earn its name once it is really compatible with a working WebKit class). That is because swift is after all not the fastest approach and C and C++ are widely used in Audio and Midi for good reasons
