### ISSUE TITLE
All messages are the same

### ISSUE THREAD

**Issue by gibbiemonster** [adamnemecek/WebMIDIKit#37]
All MIDI Messages received are the same, even though they are not.

Message: `0x0000700003bc6050`

Code:
```swift
func midiTest() {
    inputPort?.onMIDIMessage = { (list: UnsafePointer<MIDIPacketList>) in
        for packet in list {
            print("received \(packet)")
        }
		
    }	
}
```
with CoreMIDI and WebMIDIKit imports (and of course, foundation.)

**Comment by adamnemecek** [comment]
Did you check the contents of the packet? I believe that CoreMIDI reuses. the allocations.

**Comment by gibbiemonster** [comment]
Hi @adamnemecek -

I'm pretty new to this library. Could you give an example of how that would work here? Maybe it's just a CoreMIDI function?

**Comment by BlockArchitech** [comment]
Hey @adamnemecek quick update -

I think it's something to do with MIDIPacketList, but you mentioned the API's are broken. Any workaround?

**Comment by gibbiemonster** [comment]
Okay - just fixed it. The `for` loop didn't give me the packet I wanted, and just returned the same packet over and over and over again. Thanks!
