### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by aure** [adamnemecek/WebMIDIKit#38]
Hey Adam, do you think could please make this repo private or delete it?

**Comment by adamnemecek** [comment]
Why?

**Comment by aure** [comment]
Because it shows up in searches for AudioKit and MIDIKit and it is not related to either, nor is it working. You don't have to delete but if it were me I'd at least make it private. I personally would appreciate it.

**Comment by adamnemecek** [comment]
How is it not working?
